---

- name: Install openssh
  ansible.builtin.apt:
    name:
      - openssh-server
    state: present
    update_cache: true

- name: Make run directory
  ansible.builtin.file:
    path: /run/sshd
    state: directory
    mode: "0755"
  when:
    - ansible_os_family == "Debian"


- name: Configure openssh
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    validate: sshd -f %s -t
  notify:
    - Restart openssh

- name: Ensure ssh service is running and enabled
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true
